# Generated by Django 4.2.5 on 2023-10-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_time_accounting_system', '0002_alter_timesheet_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('task_title', models.CharField(max_length=300)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'История удаления таймшитов',
                'verbose_name_plural': 'Истории удаления таймшитов',
            },
        ),
    ]
