version: '3.8'

services:
  db:
    container_name: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: skill_admin
      POSTGRES_PASSWORD: Aq1234
      POSTGRES_DB: balance
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: kvashennickov.max@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
  web:
    build: .
    # command: python /app/Outsourcing_data_services/manage.py runserver 0.0.0.0:8000
    command: >
      /bin/sh -c "python /app/Outsourcing_data_services/manage.py makemigrations --no-input
      && python /app/Outsourcing_data_services/manage.py migrate --force-color
      && python /app/Outsourcing_data_services/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

volumes:
  data: